### ISSUE TITLE
TypeError powering down service

### ISSUE THREAD

**Issue by thehanimation** [aiven/aiven-client#213] opened 2021-08-14 04:34 UTC
When attempting to power down a service, an error gets thrown.

```bash
$ avn service update dev-bus --power-off
```

Result:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.5/x64/bin/avn", line 11, in <module>
    load_entry_point('aiven-client==2.3.5', 'console_scripts', 'avn')()
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/aiven/client/__main__.py", line 5, in main
    AivenCLI().main()
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/aiven/client/argx.py", line 259, in main
    sys.exit(self.run())
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/aiven/client/argx.py", line 231, in run
    return self.run_actual(args)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/aiven/client/argx.py", line 253, in run_actual
    return func()  # pylint: disable=not-callable
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/aiven/client/cli.py", line 2272, in service__update
    service = self.client.get_service(project=project, service=self.args.name)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/aiven/client/client.py", line 176, in get_service
    return self.verify(self.get, self.build_path("project", project, "service", service), result_key="service")
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/aiven/client/client.py", line 156, in build_path
    return "/" + "/".join(quote(part, safe="") for part in parts)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/aiven/client/client.py", line 156, in <genexpr>
    return "/" + "/".join(quote(part, safe="") for part in parts)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/urllib/parse.py", line 834, in quote
    return quote_from_bytes(string, safe)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/urllib/parse.py", line 859, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes`
```

**Comment by rominf** [comment] 2021-08-17 08:07
Hello @thehanimation.

Sorry for a delay.

I cannot reproduce it. Could you please try the latest version of aiven-client?

Looking forward to your reply.

**Comment by rominf** [comment] 2021-09-17 06:06
I'm closing this issue.

Feel free to reopen it any time if you will have the same problem.

Thank you for being interested in Aiven!

**Closed by rominf** 2021-09-17 06:06 UTC
